-- --------------------------------------------------------
-- ホスト:                          127.0.0.1
-- サーバーのバージョン:                   5.6.10 - MySQL Community Server (GPL)
-- サーバー OS:                      Win64
-- HeidiSQL バージョン:               9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--  テーブル test.m_user の構造をダンプしています
CREATE TABLE IF NOT EXISTS `m_user` (
  `USERID` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT 'ユーザーID',
  `USERRANK` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ユーザーランク',
  `SEX` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '性別',
  `BIRTHDAY` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '生年月日',
  `NAME` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '氏名',
  `NAMEKANA` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '氏名カナ',
  `PASSWD` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'パスワード',
  `QUESCODE` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '質問コード',
  `ANSWER` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '答え',
  `OCCUPATION` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '職業',
  `OTHEROCCUP` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '職業（その他）',
  `POSTCODE` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '郵便番号',
  `STATENAME` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '都道府県',
  `CITY` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '市区町村',
  `ADDR1` varchar(256) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '住所１',
  `ADDR2` varchar(256) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '住所２',
  `TEL` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '電話番号',
  `CELLULAR` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '携帯番号',
  `EMAIL` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'メールアドレス',
  `IEMAIL` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '携帯メールアドレス',
  `ERRMAILPCFLG` smallint(6) NOT NULL DEFAULT '0' COMMENT 'エラーメール回数（ＰＣ）',
  `ERRMAILMOBILEFLG` smallint(6) NOT NULL DEFAULT '0' COMMENT 'エラーメール回数（携帯）',
  `CARRIERCAT` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'メールキャリア種別',
  `RELCODE` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '紹介媒体',
  `RELCODEOTHER` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '紹介媒体その他',
  `FAVORITE` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'お気に入り雑誌',
  `FAVORITEOTHER` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'お気に入り雑誌その他',
  `SITECODE` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ドメインサイトコード',
  `USERAGENT1` varchar(512) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'USERAGENT(登録時)',
  `USERAGENT2` varchar(512) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'USERAGENT(直近)',
  `USECARRIERSBT` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '使用キャリア種別',
  `WITHDRAWFLG` varchar(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '退会区分',
  `WITHDRAWDATE` datetime DEFAULT NULL COMMENT '自主退会日',
  `REMARKS` varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '備考',
  `USERBLKRANK` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ユーザーブラックランク',
  `BLKUPDDATE1` datetime DEFAULT NULL COMMENT 'ブラック更新日',
  `BLKUPDDATE2` datetime DEFAULT NULL COMMENT 'ブラック更新日２',
  `BLKUPDDATE3` datetime DEFAULT NULL COMMENT 'ブラック更新日３',
  `HTMLMAIL` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ＨＴＭＬメール希望',
  `CONTRACTNUM` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '契約者番号',
  `MAGACARDHOLDER` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'マガシークカードホルダー',
  `MAGACARDAPPLYDATE` datetime DEFAULT NULL COMMENT 'MGカード紐付日',
  `MEMSBT` varchar(1) COLLATE utf8mb4_bin DEFAULT '2' COMMENT '会員種別',
  `RESEARCHREQ` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'リサーチ希望',
  `RANKJUDGEDATE` datetime DEFAULT NULL COMMENT 'ランク判定日',
  `RANKREFLECTDATE` datetime DEFAULT NULL COMMENT 'ランク反映日',
  `LASTBUYDATE` datetime DEFAULT NULL COMMENT '最終買上日',
  `PREBUYDATE` datetime DEFAULT NULL COMMENT '前回買上日',
  `CRTDATE` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '登録日',
  `CRTEMPLCODE` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '登録社員コード',
  `CRTTERMID` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '登録端末ID',
  `UPDDATE` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '更新日',
  `UPDEMPLCODE` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '更新社員コード',
  `UPDTERMID` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '更新端末ID',
  `DELFLG` tinyint(4) DEFAULT '0' COMMENT '削除フラグ',
  `ONECLICKREGISTFLG` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'ワンクリック登録フラグ',
  `BLK_COUNT` smallint(6) DEFAULT '0' COMMENT 'ブラックカウント',
  `BLKUPD_EMPLCODE` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ブラック更新者',
  `UPDATE_MUSER_DATE` datetime DEFAULT NULL COMMENT '会員情報更新日',
  `UPDATE_MUSER_EMPLCODE` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '会員情報更新者',
  `FORCED_WITHDRAWDATE` datetime DEFAULT NULL COMMENT '強制退会日',
  `UNDELIVEREDMAIL_MOBILE_FLG` tinyint(4) DEFAULT '0' COMMENT 'モバイルメール受信フラグ',
  `UNDELIVEREDMAIL_PC_FLG` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'メール不達（PC）フラグ',
  `UNDELIVEREDMAIL_MB_FLG` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'メール不達（MB）フラグ',
  `USER_STATUS_CLASS` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '会員状態区分',
  `USER_STATUS` tinyint(4) DEFAULT NULL COMMENT '会員ステータス',
  `RESENDMAIL_FLG` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'ランクアップ前メール送信済フラグ',
  `LASTORDERDATE` datetime DEFAULT NULL COMMENT '商品最終購入日',
  `ADDRUNKNOWN_FLG` tinyint(4) DEFAULT NULL COMMENT '住所不明フラグ',
  `SIMPLE_REGIST_DATE` datetime DEFAULT NULL COMMENT '簡易登録完了日時',
  `REGIST_DATE` datetime DEFAULT NULL COMMENT '本登録完了日時',
  `WITHDRAWREASON` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '退会理由',
  `WITHDRAWREASONFREE` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '退会理由自由記入',
  `FIRST_PURCHASE_STATUS` tinyint(4) DEFAULT NULL COMMENT '初回購入ステータス',
  `FIRST_ARRIVAL_DATE` datetime DEFAULT NULL COMMENT '初回着荷日',
  `DFASHION_ORDERER_ID` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'dファッション注文者ID',
  `COOPERATION_USER_KBN` tinyint(4) NOT NULL DEFAULT '0' COMMENT '外部連動ユーザ区分',
  `PREVIOUS_USERRANK` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '更新前ユーザーランク',
  PRIMARY KEY (`USERID`),
  KEY `IDX_M_USER_01` (`EMAIL`,`ERRMAILPCFLG`,`WITHDRAWFLG`,`HTMLMAIL`),
  KEY `IDX_M_USER_02` (`IEMAIL`,`ERRMAILMOBILEFLG`,`WITHDRAWFLG`),
  KEY `IDX_M_USER_03` (`WITHDRAWFLG`),
  KEY `IDX_M_USER_04` (`STATENAME`,`CITY`),
  KEY `IDX_M_USER_05` (`CITY`,`USERBLKRANK`,`WITHDRAWFLG`),
  KEY `IDX_M_USER_06` (`CONTRACTNUM`,`DELFLG`),
  KEY `IDX_M_USER_07` (`USERID`,`EMAIL`,`UNDELIVEREDMAIL_PC_FLG`,`USERBLKRANK`,`WITHDRAWFLG`,`DELFLG`,`NAME`),
  KEY `IDX_M_USER_08` (`USERID`,`IEMAIL`,`UNDELIVEREDMAIL_MB_FLG`,`USERBLKRANK`,`WITHDRAWFLG`,`DELFLG`,`NAME`),
  KEY `IDX_M_USER_09` (`NAME`),
  KEY `IDX_M_USER_10` (`NAMEKANA`),
  KEY `IDX_M_USER_11` (`TEL`),
  KEY `IDX_M_USER_12` (`CELLULAR`),
  KEY `IDX_M_USER_13` (`DFASHION_ORDERER_ID`),
  KEY `IDX_M_USER_14` (`COOPERATION_USER_KBN`),
  KEY `IDX_M_USER_15` (`STATENAME`,`CITY`,`NAME`,`COOPERATION_USER_KBN`,`DELFLG`,`USERBLKRANK`,`WITHDRAWFLG`,`TEL`,`CELLULAR`),
  KEY `IDX_M_USER_16` (`BLKUPDDATE1`,`USERBLKRANK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC COMMENT='ユーザーマスタ';

-- テーブル test.m_user: ~5 rows (approximately) のデータをダンプしています
DELETE FROM `m_user`;
/*!40000 ALTER TABLE `m_user` DISABLE KEYS */;
INSERT INTO `m_user` (`USERID`, `USERRANK`, `SEX`, `BIRTHDAY`, `NAME`, `NAMEKANA`, `PASSWD`, `QUESCODE`, `ANSWER`, `OCCUPATION`, `OTHEROCCUP`, `POSTCODE`, `STATENAME`, `CITY`, `ADDR1`, `ADDR2`, `TEL`, `CELLULAR`, `EMAIL`, `IEMAIL`, `ERRMAILPCFLG`, `ERRMAILMOBILEFLG`, `CARRIERCAT`, `RELCODE`, `RELCODEOTHER`, `FAVORITE`, `FAVORITEOTHER`, `SITECODE`, `USERAGENT1`, `USERAGENT2`, `USECARRIERSBT`, `WITHDRAWFLG`, `WITHDRAWDATE`, `REMARKS`, `USERBLKRANK`, `BLKUPDDATE1`, `BLKUPDDATE2`, `BLKUPDDATE3`, `HTMLMAIL`, `CONTRACTNUM`, `MAGACARDHOLDER`, `MAGACARDAPPLYDATE`, `MEMSBT`, `RESEARCHREQ`, `RANKJUDGEDATE`, `RANKREFLECTDATE`, `LASTBUYDATE`, `PREBUYDATE`, `CRTDATE`, `CRTEMPLCODE`, `CRTTERMID`, `UPDDATE`, `UPDEMPLCODE`, `UPDTERMID`, `DELFLG`, `ONECLICKREGISTFLG`, `BLK_COUNT`, `BLKUPD_EMPLCODE`, `UPDATE_MUSER_DATE`, `UPDATE_MUSER_EMPLCODE`, `FORCED_WITHDRAWDATE`, `UNDELIVEREDMAIL_MOBILE_FLG`, `UNDELIVEREDMAIL_PC_FLG`, `UNDELIVEREDMAIL_MB_FLG`, `USER_STATUS_CLASS`, `USER_STATUS`, `RESENDMAIL_FLG`, `LASTORDERDATE`, `ADDRUNKNOWN_FLG`, `SIMPLE_REGIST_DATE`, `REGIST_DATE`, `WITHDRAWREASON`, `WITHDRAWREASONFREE`, `FIRST_PURCHASE_STATUS`, `FIRST_ARRIVAL_DATE`, `DFASHION_ORDERER_ID`, `COOPERATION_USER_KBN`, `PREVIOUS_USERRANK`) VALUES
	('test5555', '1', '0', '19800101', 'てすと　てすと', 'テスト　テスト', 'f735292e5d7e3a3a2d11d2f1085510ba', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'test@test.jp', 'test@ezweb.ne.jp', 0, 0, '02', '0', NULL, NULL, NULL, '0000000000', 'Mozilla/5.0 (Windows NT 6.1; rv:9.0.1) Gecko/20100101 Firefox/9.0.1', 'Mozilla/5.0 (Windows NT 6.1; rv:9.0.1) Gecko/20100101 Firefox/9.0.1', '01', '0', NULL, NULL, '0', NULL, NULL, NULL, '1', NULL, '2', NULL, '2', NULL, NULL, NULL, NULL, NULL, '2012-02-03 16:27:04.000000', NULL, NULL, '2012-02-03 16:27:04.000000', NULL, NULL, 0, 0, NULL, NULL, NULL, 'admin12345', NULL, NULL, 0, 0, NULL, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, 0, NULL),
	('test5556', '2', '0', '19800101', 'てすと　てすと', 'テスト　テスト', 'f735292e5d7e3a3a2d11d2f1085510ba', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'test@test.jp', 'test@ezweb.ne.jp', 0, 0, '02', '0', NULL, NULL, NULL, '0000000000', 'Mozilla/5.0 (Windows NT 6.1; rv:9.0.1) Gecko/20100101 Firefox/9.0.1', 'Mozilla/5.0 (Windows NT 6.1; rv:9.0.1) Gecko/20100101 Firefox/9.0.1', '01', '0', NULL, NULL, '0', NULL, NULL, NULL, '1', NULL, '2', NULL, '2', NULL, NULL, NULL, NULL, NULL, '2012-02-03 16:27:04.000000', NULL, NULL, '2012-02-03 16:27:04.000000', NULL, NULL, 0, 0, NULL, NULL, NULL, 'admin12345', NULL, NULL, 0, 0, NULL, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, 0, NULL),
	('test5557', '3', '0', '19800101', 'てすと　てすと', 'テスト　テスト', 'f735292e5d7e3a3a2d11d2f1085510ba', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'test@test.jp', 'test@ezweb.ne.jp', 0, 0, '02', '0', NULL, NULL, NULL, '0000000000', 'Mozilla/5.0 (Windows NT 6.1; rv:9.0.1) Gecko/20100101 Firefox/9.0.1', 'Mozilla/5.0 (Windows NT 6.1; rv:9.0.1) Gecko/20100101 Firefox/9.0.1', '01', '0', NULL, NULL, '0', NULL, NULL, NULL, '1', NULL, '2', NULL, '2', NULL, NULL, NULL, NULL, NULL, '2012-02-03 16:27:04.000000', NULL, NULL, '2012-02-03 16:27:04.000000', NULL, NULL, 0, 0, NULL, NULL, NULL, 'admin12345', NULL, NULL, 0, 0, NULL, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, 0, NULL),
	('test5558', '4', '0', '19800101', 'てすと　てすと', 'テスト　テスト', 'f735292e5d7e3a3a2d11d2f1085510ba', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'test@test.jp', 'test@ezweb.ne.jp', 0, 0, '02', '0', NULL, NULL, NULL, '0000000000', 'Mozilla/5.0 (Windows NT 6.1; rv:9.0.1) Gecko/20100101 Firefox/9.0.1', 'Mozilla/5.0 (Windows NT 6.1; rv:9.0.1) Gecko/20100101 Firefox/9.0.1', '01', '0', NULL, NULL, '0', NULL, NULL, NULL, '1', NULL, '2', NULL, '2', NULL, NULL, NULL, NULL, NULL, '2012-02-03 16:27:04.000000', NULL, NULL, '2012-02-03 16:27:04.000000', NULL, NULL, 0, 0, NULL, NULL, NULL, 'admin12345', NULL, NULL, 0, 0, NULL, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, 0, NULL),
	('test5559', '5', '0', '19800101', 'てすと　てすと', 'テスト　テスト', 'f735292e5d7e3a3a2d11d2f1085510ba', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'test@test.jp', 'test@ezweb.ne.jp', 0, 0, '02', '0', NULL, NULL, NULL, '0000000000', 'Mozilla/5.0 (Windows NT 6.1; rv:9.0.1) Gecko/20100101 Firefox/9.0.1', 'Mozilla/5.0 (Windows NT 6.1; rv:9.0.1) Gecko/20100101 Firefox/9.0.1', '01', '0', NULL, NULL, '0', NULL, NULL, NULL, '1', NULL, '2', NULL, '2', NULL, NULL, NULL, NULL, NULL, '2012-02-03 16:27:04.000000', NULL, NULL, '2012-02-03 16:27:04.000000', NULL, NULL, 0, 0, NULL, NULL, NULL, 'admin12345', NULL, NULL, 0, 0, NULL, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, 0, NULL);
/*!40000 ALTER TABLE `m_user` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
