Vagrant.configure(2) do |config|

  #### プラグインの設定
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  #### サーバ設定
  config.vm.box = "CentOS7"
  #### config.vm.box_url = "https://drive.google.com/file/d/1A410wSZZ7hMhe2W0yqrL6NTTIvPzzQQm/view?usp=sharing"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  config.vm.provision "ansible_local" do |ansible|

    ansible.playbook        = "provisioning/nginx_mariadb_plyabook.yml"
    ansible.install         = true
    ansible.inventory_path  = "provisioning/hosts"
    ansible.limit           = "all"
    ansible.verbose         = "v"

  end

  config.vm.synced_folder "../www", "/usr/share/nginx/html", owner: "vagrant", group: "vagrant", mount_options: ['dmode=777','fmode=755']

end
